Added more example files for /etc/kernel
This commit adds a set of example script that wll automatically handle
/lib/mocules/$VERSION/build -- setting it to point to the kernel headers
files when either the kernel image or the kernel header packages are
installed, and cleaning the link up when either of these packaes are
removed.

Signed-Off-By: Manoj Srivastava <srivasta@debian.org>

diff --git a/kernel/examples/etc/kernel/header_postinst.d/link b/kernel/examples/etc/kernel/header_postinst.d/link
--- a/kernel/examples/etc/kernel/header_postinst.d/link
+++ b/kernel/examples/etc/kernel/header_postinst.d/link
@@ -1,8 +1,6 @@
 #! /bin/bash
 
 version=$1
-image=$2
-package=$3
 
 if [ -n "$DEB_MAINT_PARAMS" ]; then
     eval set -- "$DEB_MAINT_PARAMS"
@@ -30,32 +28,39 @@ case $architecture in
         :
 esac
 
+# passing the kernel version is required
+[ -z "$version" ] && exit 1
 
-if [ -d "/usr/src/linux-headers-$version" ]; then
-    # See if we have a kernel image of the same version already
-    # installed.
-    if  [ -d "/lib/modules/$version"  ] &&
-        [ ! -e "/lib/modules/$version/build" ]; then
-        if ! ln -s "/usr/src/linux-headers-$version"  "/lib/modules/$version/build" ; then
-            echo >&2 "Could not link /usr/src/linux-headers-$version to /lib/modules/$version/build";
-        fi
+MODULEDIR=/lib/modules/$version
+HEADERDIR=/usr/src/linux-headers-$version
+
+test -d $HEADERDIR || exit 0
+
+
+# See if we have a kernel image of the same version already
+# installed.
+if  [ -d "$MODULEDIR"  ] &&
+    [ ! -e "$MODULEDIR/build" ]; then
+    if ! ln -s "$HEADERDIR"  "$MODULEDIR/build" ; then
+        echo >&2 "Could not link $HEADERDIR to $MODULEDIR/build";
     fi
-    # Make sure the asm link is sane
-    if [ ! -d "/usr/src/linux-headers-$version/include" ]; then
-        echo >&2 "/usr/src/linux-headers-$version/include does not exist"
-        exit 1
-    fi
-    cd "/usr/src/linux-headers-$version/include"
-    if [ ! -s "asm-$architecture" ]; then
-        echo >&2 "/usr/src/linux-headers-$version/include/asm-$architecture does not exist"
-    elif [ -e 'asm' ]; then
-        if [ ! -L 'asm' ]; then
-            echo >&2 "/usr/src/linux-headers-$version/include/asm is not a symbolic link"
-        else
-            rm -f asm
-            ln -sf  "asm-$architecture" 'asm'
-        fi
-    fi    
 fi
+
+# Make sure the asm link is sane
+if [ ! -d "$HEADERDIR/include" ]; then
+    echo >&2 "$HEADERDIR/include does not exist"
+    exit 1
+fi
+cd "$HEADERDIR/include"
+if [ ! -s "asm-$architecture" ]; then
+    echo >&2 "$HEADERDIR/include/asm-$architecture does not exist"
+elif [ -e 'asm' ]; then
+    if [ ! -L 'asm' ]; then
+        echo >&2 "$HEADERDIR/include/asm is not a symbolic link"
+    else
+        rm -f asm
+        ln -sf  "asm-$architecture" 'asm'
+    fi
+fi    
 
 exit 0
