only trigger initramfs removal on 'remove', and not again on purge
Also, since this is a remove, and the initramfs call is a convenience
function for clear out  initramfs-tool metadata, we do not care if it
actually worked. We just make the best effort at clean up, but do not let
the cleanup abort the process.

Signed-Off-By: Manoj Srivastava <srivasta@debian.org>

diff --git a/kernel/examples/etc/kernel/postrm.d/initramfs b/kernel/examples/etc/kernel/postrm.d/initramfs
--- a/kernel/examples/etc/kernel/postrm.d/initramfs
+++ b/kernel/examples/etc/kernel/postrm.d/initramfs
@@ -8,10 +8,11 @@ fi
 version="$1"
 vmlinuz_location="$2"
 
+# Note we only trigger on a remove, and not again on purge
 if [ -n "$DEB_MAINT_PARAMS" ]; then
     eval set -- "$DEB_MAINT_PARAMS"
     case "$1" in
-        remove|purge)
+        remove)
             : echo nop
             ;;
         *)
@@ -28,5 +29,5 @@ if [  -n "$vmlinuz_location" ]; then
     bootarg="-b $boot"
 fi
 
-# 
-update-initramfs -d -k "$version" $bootarg
+# try and remove the initramfs, and do not care if it fails
+update-initramfs -d -k "$version" $bootarg || true
