Make sure that initramfs hook script are safe
This means they will not error out if the corresponding initramfs
generator is not installed. This way, people may install both the
initramfs and yaird hook scripts, and they will only trigger if the
generator is actually installed.

Signed-Off-By: Manoj Srivastava <srivasta@debian.org>

diff --git a/kernel/examples/etc/kernel/postrm.d/initramfs b/kernel/examples/etc/kernel/postrm.d/initramfs
--- a/kernel/examples/etc/kernel/postrm.d/initramfs
+++ b/kernel/examples/etc/kernel/postrm.d/initramfs
@@ -30,4 +30,10 @@ if [  -n "$vmlinuz_location" ]; then
 fi
 
 # try and remove the initramfs, and do not care if it fails
-update-initramfs -d -k "$version" $bootarg || true
+if which update-initramfs >/dev/null ; then
+    update-initramfs -d -k "$version" $bootarg || true
+fi
+# try and remove the initramfs, and do not care if it fails
+if [ -e "$boot/initrd.img-$version" ]; then
+   rm -f "$boot/initrd.img-$version"  || true
+fi
